In [20]:
"""
Завдання 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
"""

import numpy as np

my_vector = np.arange(1, 11)
my_vector_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10], dtype=int)

print(my_vector)
print(my_vector_2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
"""
Завдання 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
"""

my_matrix = np.zeros((3, 3))

print(my_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
"""
Завдання 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
"""

my_array = np.random.randint(1, 11, size=(5, 5))

print(my_array)

[[ 6  8  3  5  6]
 [ 1  3  5 10  8]
 [10  4  4  3  9]
 [ 6  1  3  6  3]
 [ 1  2  4  8  9]]


In [23]:
"""
Завдання 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
"""

my_array = np.random.rand(4, 4)

print(my_array)

[[0.33215    0.36140828 0.73772478 0.17245313]
 [0.56391642 0.5998612  0.47722133 0.0771755 ]
 [0.60321566 0.64432319 0.49447885 0.884516  ]
 [0.17303419 0.66473699 0.18398547 0.46289344]]


In [24]:
"""
Завдання 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
та виконайте на них поелементні операції додавання, віднімання та множення.
"""

array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

print("Масив 1:", array1)
print("Масив 2:", array2)

sum_result = array1 + array2
print("Додавання масивів:", sum_result)

subtract_result = array1 - array2
print("Віднімання масивів:", subtract_result)

multiply_result = array1 * array2
print("Множення масивів:", multiply_result)

Масив 1: [ 4  3  6 10 10]
Масив 2: [9 2 8 7 7]
Додавання масивів: [13  5 14 17 17]
Віднімання масивів: [-5  1 -2  3  3]
Множення масивів: [36  6 48 70 70]


In [25]:
"""
Завдання 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
"""

vector1 = np.random.randint(1, 111, size=7)
vector2 = np.random.randint(1, 111, size=7)

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)

dot_product_result = np.dot(vector1, vector2)
print("Скалярний добуток:", dot_product_result)

Вектор 1: [ 32  96 101  68  88  18  36]
Вектор 2: [ 38 107  85  52 107  74  67]
Скалярний добуток: 36769


In [26]:
"""
Завдання 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
та перемножте їх між собою.
"""

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

product_result = np.dot(matrix1, matrix2)
print("\nРезультат перемноження:")
print(product_result)

Матриця 1:
[[ 2 10]
 [ 1  8]]

Матриця 2:
[[ 6 10  8]
 [10  5  3]]

Результат перемноження:
[[112  70  46]
 [ 86  50  32]]


In [27]:
"""
Завдання 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
"""

matrix = np.random.randint(1, 11, size=(2, 2))

print(matrix, '\n')
print(matrix.T)

[[1 3]
 [7 9]] 

[[1 7]
 [3 9]]


In [28]:
"""
Завдання 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
"""

matrix = np.round(np.random.rand(4, 4), 3)

print(matrix, '\n')
print(matrix.T)

[[0.648 0.82  0.636 0.397]
 [0.026 0.186 0.908 0.241]
 [0.022 0.792 0.743 0.23 ]
 [0.518 0.427 0.107 0.309]] 

[[0.648 0.026 0.022 0.518]
 [0.82  0.186 0.792 0.427]
 [0.636 0.908 0.743 0.107]
 [0.397 0.241 0.23  0.309]]


In [29]:
"""
Завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
та перемножте матрицю на вектор.
"""

import numpy as np

matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)

print("Матриця :")
print(matrix)
print("\nВектор:")
print(vector)

result = np.dot(matrix, vector)

print("\nРезультат перемноження матриці на вектор:")
print(result)

Матриця :
[[8 4 4 1]
 [6 4 1 6]
 [8 1 1 7]]

Вектор:
[ 1  3 10  2]

Результат перемноження матриці на вектор:
[62 40 35]


In [30]:
"""
Завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3,
заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
"""

matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

print("Матриця :")
print(matrix)
print("\nВектор:")
print(vector)

result = np.dot(matrix, vector)

print("\nРезультат перемноження матриці на вектор:")
print(result)

Матриця :
[[0.88081046 0.50996189 0.70577846]
 [0.09588981 0.29569846 0.73832101]]

Вектор:
[0.00391939 0.87364402 0.42434605]

Результат перемноження матриці на вектор:
[0.74847169 0.57201462]


In [31]:
"""
Завдання 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
та виконайте їхнє поелементне множення.
"""

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

result = matrix1*matrix2

print("\nРезультат перемноження матриці на вектор:")
print(result)

Матриця 1:
[[ 9  3]
 [ 7 10]]

Матриця 2:
[[ 1  5]
 [10  1]]

Результат перемноження матриці на вектор:
[[ 9 15]
 [70 10]]


In [32]:
"""
Завдання 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
"""

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

result = matrix1+matrix2

print("\nРезультат перемноження матриці на вектор:")
print(result)

Матриця 1:
[[ 5  4]
 [10  3]]

Матриця 2:
[[1 7]
 [5 8]]

Результат перемноження матриці на вектор:
[[ 6 11]
 [15 11]]


In [33]:
"""
Завдання 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100
та знайдіть суму елементів матриці.
"""

matrix = np.random.randint(1, 101, size=(5, 5))

print("Матриця:")
print(matrix)

sum_matrix = np.sum(matrix)

print("\nСума елементів матриці:", sum_matrix)

Матриця:
[[22 26 65 61 14]
 [51 95 77 57 54]
 [99 96 74 81 90]
 [73 99 48 98 16]
 [69 70 47 64 84]]

Сума елементів матриці: 1630


In [34]:
"""
Завдання 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
"""

matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

difference_matrix = matrix1 - matrix2

print("\nРізниця матриць:")
print(difference_matrix)

Матриця 1:
[[ 8  8  8  8]
 [ 6  3  4  7]
 [ 3 10 10 10]
 [ 3  3  8  9]]

Матриця 2:
[[ 1  3  3  5]
 [10  7  1 10]
 [ 1  8  8  1]
 [ 9  8  3  3]]

Різниця матриць:
[[ 7  5  5  3]
 [-4 -4  3 -3]
 [ 2  2  2  9]
 [-6 -5  5  6]]


In [35]:
"""
Завдання 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик,
що містить суму елементів кожного рядка матриці.
"""

matrix = np.random.rand(3, 3)

print("Матриця:")
print(matrix)

row_sums = np.sum(matrix, axis=1, keepdims=True)

print("\nСума елементів кожного рядка:")
print(row_sums)

Матриця:
[[0.01947749 0.42608414 0.70619044]
 [0.21140686 0.41287365 0.77123405]
 [0.72153466 0.89155945 0.05572379]]

Сума елементів кожного рядка:
[[1.15175207]
 [1.39551455]
 [1.6688179 ]]


In [36]:
"""
Завдання 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
"""

matrix = np.random.randint(1, 111, size=(3, 4))

print("Матриця:")
print(matrix)

squares_matrix = np.square(matrix)

print("\nМатриця з квадратами чисел:")
print(squares_matrix)

Матриця:
[[104  91  95  10]
 [ 64  85  80  45]
 [  8  35   2  40]]

Матриця з квадратами чисел:
[[10816  8281  9025   100]
 [ 4096  7225  6400  2025]
 [   64  1225     4  1600]]


In [37]:
"""
Завдання 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50
та знайдіть вектор з квадратними коренями цих чисел.
"""

vector = np.random.randint(1, 51, size=4)

print("Вектор:")
print(vector)

sqrt_vector = np.sqrt(vector)

print("\nВектор з квадратними коренями:")
print(sqrt_vector)

Вектор:
[39 48  1 47]

Вектор з квадратними коренями:
[6.244998   6.92820323 1.         6.8556546 ]
