In [39]:
"""
Завдання 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
"""

import numpy as np

my_vector = np.arange(1, 11)
my_vector_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10], dtype=int)

print(my_vector)
print(my_vector_2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [40]:
"""
Завдання 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
"""

my_matrix = np.zeros((3, 3))

print(my_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
"""
Завдання 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
"""

my_array = np.random.randint(1, 11, size=(5, 5))

print(my_array)

[[ 5  9  9  6  3]
 [ 8  9  3  7  4]
 [ 4  7  3 10  6]
 [ 5  5  3  1  7]
 [ 9  5  9  2  1]]


In [36]:
"""
Завдання 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
"""

my_array = np.random.rand(4, 4)

print(my_array)

[[0.06934156 0.44379254 0.3769385  0.64642597]
 [0.55297336 0.67452654 0.066914   0.75034642]
 [0.44020394 0.50405135 0.44744662 0.7672892 ]
 [0.88435414 0.85783092 0.54280262 0.19148378]]


In [37]:
"""
Завдання 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
та виконайте на них поелементні операції додавання, віднімання та множення.
"""

array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

print("Масив 1:", array1)
print("Масив 2:", array2)

sum_result = array1 + array2
print("Додавання масивів:", sum_result)

subtract_result = array1 - array2
print("Віднімання масивів:", subtract_result)

multiply_result = array1 * array2
print("Множення масивів:", multiply_result)

Масив 1: [4 1 2 1 2]
Масив 2: [10  6  1 10 10]
Додавання масивів: [14  7  3 11 12]
Віднімання масивів: [-6 -5  1 -9 -8]
Множення масивів: [40  6  2 10 20]


In [38]:
"""
Завдання 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
"""

vector1 = np.random.randint(1, 111, size=7)
vector2 = np.random.randint(1, 111, size=7)

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)

dot_product_result = np.dot(vector1, vector2)
print("Скалярний добуток:", dot_product_result)

Вектор 1: [ 37  39  90  63  53  42 100]
Вектор 2: [ 30 102   2  12  85 107 108]
Скалярний добуток: 25823


In [23]:
"""
Завдання 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
та перемножте їх між собою.
"""

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

product_result = np.dot(matrix1, matrix2)
print("\nРезультат перемноження:")
print(product_result)

Матриця 1:
[[1 2]
 [7 7]]

Матриця 2:
[[4 6 2]
 [8 8 6]]

Результат перемноження:
[[20 22 14]
 [84 98 56]]


In [25]:
"""
Завдання 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
"""

matrix = np.random.randint(1, 11, size=(2, 2))

print(matrix, '\n')
print(matrix.T)

[[ 5  4]
 [10  3]] 

[[ 5 10]
 [ 4  3]]


In [32]:
"""
Завдання 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
"""

matrix = np.round(np.random.rand(4, 4), 3)

print(matrix, '\n')
print(matrix.T)

[[0.791 0.296 0.063 0.738]
 [0.966 0.064 0.707 0.195]
 [0.455 0.896 0.835 0.564]
 [0.282 0.989 0.361 0.47 ]] 

[[0.791 0.966 0.455 0.282]
 [0.296 0.064 0.896 0.989]
 [0.063 0.707 0.835 0.361]
 [0.738 0.195 0.564 0.47 ]]
